### ISSUE TITLE
Output opamps IC1 and IC2 get very hot when no cables plugged in

### ISSUE THREAD

**Issue by Jagmills** [Shayshez/1uO_c#1]
Hi!

I think the cause is the output jacks' switches are grounded. When an unconnected cable is plugged in to every output, the ICs are a normal temperature.
The original o_C schematic shows that these pins are not connected.

A solution is to desolder the jacks and remove the switching plate or pin.

**Comment by Shayshez** [comment]
Fixed in board v 1.3
